version: '3'
services:
  qiankun-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: qiankun-main
    container_name: qiankun-main
    ports:
      - '8089:8088'
      - '6326:6324'
